import Image from "next/image";
import Link from "next/link";
import styles from './page.module.css'


// async function getData() {
//   const res = await fetch('https://dummyjson.com/products')
//   if (!res.ok) {
//     throw new Error('Failed to fetch data')
//   }
//   return res.json()
// }
export const metadata = {
  title: 'Hexashop-products',
  description: 'Generated by create next app',
}

export default async function Blog() {
  const response=await fetch("https://fakestoreapi.com/products");
  const products=await response.json();
   
  

  return (
    <div className={styles.mainContainer}>
      {
        products.map(product => (

          <Link href="/blog/id" className={styles.post} key={product.id}>
        <div className={styles.imageContainer}>
          <Image
            className={styles.image}
            src={product.image}
            fill={true}
            alt="post image"
          />
        </div>  
          <div className={styles.contant}>
            <h1 className={styles.title}> {product.title}</h1>
            <p className={styles.text}>{product.description}</p>
          </div>
        
      </Link>
        ))
      }
      
    </div>
  )
}
